### ISSUE TITLE
I am trying to run this code but consistently getting errors.

### ISSUE THREAD

**Issue by aliman80** [nasir6/zero_shot_detection#15]
Can you guide me the relevant procedure. I have created environment ,download datasets, set the paths and try to run detector code.
I can not use docker as my univeristy doesnot allow.

regards

**Comment by youzi260** [comment]
How are you doing with this code? I have a big problem with loss

**Comment by ChiliSauceforCats** [comment]
Excuse me, I can't find this file, what should I do?

Traceback (most recent call last):
  File "/home/luyue/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'VOC/fasttext_multilabels_4.npy'

**Comment by youzi260** [comment]
可能是你的路径，换成绝对路径试试吧
| |
张婷婷
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/12/2022 ***@***.***> wrote：

Excuse me, I can't find this file, what should I do?

Traceback (most recent call last):
File "/home/luyue/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] 没有那个文件或目录: 'VOC/fasttext_multilabels_4.npy'
